add switcher mode
Sparted/l10ns pull request #2
Opened 2017-08-10 14:52 UTC by joan-saum

2017-08-10 14:53 UTC, joan-saum commented
![](https://github.trello.services/images/mini-trello-icon.png) [Replace the language switcher to a Translate / Validate / Read Mode [9]](https://trello.com/c/YbazO89i/92-replace-the-language-switcher-to-a-translate-validate-read-mode-9)

2017-08-22 18:10 UTC, cadesalaberry requested changes

2017-08-22 18:10 UTC, cadesalaberry commented on example/javascript/index.js
> +
Keep the same examples.

2017-08-22 18:10 UTC, cadesalaberry commented on example/javascript/localizations/en-GB.json
> +      "alloha"
Keep the same examples. Only `"validated": false,` should be added

2017-08-22 18:10 UTC, cadesalaberry commented on interface/configurations/app.js
> +        response.redirect('/' + project.defaultLanguage + '/Validate/localizations');
Always use lowercases for URLs

2017-08-22 18:10 UTC, cadesalaberry commented on interface/contents/LeftMenu/LeftMenuView.js
> +
Keep the set timeout. Why are we not using a variable instead of path ?

2017-08-22 18:10 UTC, cadesalaberry commented on interface/contents/locales/Locales.dot
> +    <div class="locales-dropdown-caret">
Validation/Translation/All ?

2017-08-22 18:10 UTC, cadesalaberry commented on interface/contents/locales/LocalesView.js
> -
Keep space.

2017-08-22 18:10 UTC, cadesalaberry commented on interface/contents/locales/LocalesView.js
> +      window.location.pathname = path.join('/');
Why not use app.navigate() ?

2017-08-25 08:51 UTC, merged